#page title
page_title: CrissCross # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 1234793120 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link: https://gracelam344752.typeform.com/to/LnShnQ31 # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link:
  https://gracelam344752.typeform.com/to/LnShnQ31 # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: CrissCross App # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Neighborhood gig economy at your doorstep.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

your_name: CrissCross Team
your_link: https://gracelam344752.typeform.com/to/LnShnQ31
your_city: Berkeley
email_address: gracelam@berkeley.edu
facebook_username:
instagram_username: graceyraspberry
twitter_username: graceyraspberry
github_username:
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Fast & relevant gigs
    description: Scroll through teen profiles for a particular gig. Custom posting for specific gig requests.
    fontawesome_icon_name: magic

  - title: Dynamic portfolio
    description: Gone are the days of boring resume templates. Choose your potential hiree by viewing quick videos and clips that demonstrate their best skills!
    fontawesome_icon_name: mobile

  - title: Effortless communication, payment, and reviews
    description: Private messaging channel to communicate with hiree. Secure payment service to handle all transactions. Anonymous reviews with a badge system to reward progress and hustle.
    fontawesome_icon_name: play-circle

  - title: Minimalistic yet expressive UI
    description: Dashboard-centric app that removes all unnecessary buttons and widgets. Carefully selected color palettes and animations for a fluid app experience.
    fontawesome_icon_name: sync

  - title: Immediate, inexpensive workers
    description: We connect high school and college students (like yours!) from the neighborhood to any gig request you may have, bringing a versatile, energetic pool of workers your way.
    fontawesome_icon_name: adjust

  - title: Stronger neighborhood network
    description: With decreasing trends of neighborhood engagement, the services that these teens provide will contribute to a tighter neighborhood community.
    fontawesome_icon_name: star

  - title: Best investment in next generation
    description: By requesting gigs, you have a direct influence in the development of your teens' interpersonal skills and work experience. Given the flexible nature of gigs, teens won't have to worry about losing time on schoolwork!
    fontawesome_icon_name: arrow-alt-circle-down

  # - title                                 : Social Links
  #   description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : link

  # - title                                 : FontAwesome Support
  #   description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : info-circle

  - title: # New Feature Title
    description: # New Feature Description
    fontawesome_icon_name: # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Theme Settings
topbar_color: "#e6e6e6"
topbar_transparency: 0.9
topbar_title_color: "#000000"

cover_image: # assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color: "#ffffff"
cover_overlay_transparency: 0.8

device_color: white # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#000000"
app_price_color: "#000000"
app_description_color: "#666666"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
